# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "grantnicholas.io"
description: > # this means to ignore newlines until "email:"
   A blog about my adventures in programming

email: grantnicholas2015@u.northwestern.edu
#blog logo
# logo: "/-blog/assets/images/df_logo.jpg"
logo: "/assets/images/GN.jpg"
# blog cover
# cover: "/-blog/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
cover: "/assets/images/cover_med.jpg"

name: 'Grant Nicholas'
author: 'Grant Nicholas'
author_image: "/assets/images/grant_nicholas.jpg"

paginate:	5

url: "http://grantnicholas.github.io/" # the base hostname & protocol for your site
# baseurl: "/-blog"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    # url:	https://twitter.com/dirkfabisch
    # desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    # url:	https://facebook.com/???
    # desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/grantnicholas
    desc:	Look at my projects on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
